module.exports = {
	TODAY_WORDS : ['ngày hôm nay', 'hôm nay', 'sáng nay', 'tối nay', 'trưa nay'],
	TOMORROW_WORDS : ['sáng mai', 'tối mai', 'trưa mai', 'ngày mai'],
	AFTER_TOMORROW_WORDS : ['ngày kia'],
	THISWEEK_WORDS : ['tuần này'],
	NEXTWEEK_WORDS : ['tuần tới', 'tuần sau'],
	
	MONDAY_WORDS : ['thứ 2', 'thứ2', 'thứ hai', 'thu hai', 'thu 2', 'thư hai', 'thư 2', 't2', 't 2', 'th2', 'th 2'],
	TUESDAY_WORDS : ['thứ 3', 'thứ3', 'thứ ba', 'thu ba', 'thu 3', 'thư ba', 'thư 3', 't3', 't 3', 'th3', 'th 3'],
	WED_WORDS : ['thứ 4', 'thứ4', 'thứ tư', 'thu tư', 'thu 4', 'thư tư', 'thư 4', 't4', 't 4', 'th4', 'th 4'],
	THURSDAY_WORDS : ['thứ 5', 'thứ5', 'thứ năm', 'thu năm', 'thu 5', 'thư năm', 'thư 5', 't5', 't 5', 'th5', 'th 5'],
	FRIDAY_WORDS : ['thứ 6', 'thứ6', 'thứ sáu', 'thu sáu', 'thu 6', 'thư sáu', 'thư 6', 't6', 't 6', 'th6', 'th 6'],
	SATURDAY_WORDS : ['thứ 7', 'thứ7', 'thứ bảy', 'thu bảy', 'thu 7', 'thư bảy', 'thư 7', 't7', 't 7', 'th7', 'th 7'],
	SUNDAY_WORDS : ['chủ nhật', 'chu nhat', 'cn', 'CN'],
	
	LOCATION_START_WORDS : ['sân', 'san ', 'khu vực', 'khu vuc', 'đường', 'khu ', 'mạn ', 'địa chỉ', 'đia chi', 'dia chi', "kvuc"],
	LOCATION_END_WORDS : ['.', "\n", "\r\n", 'tối', 'chiều', 'đội', 'trình độ', 'học lực', 'tỷ lệ', 'tỉ lệ'],
	
	TYPE_DI_KHACH : ['đi khách', 'di khach'],
	TYPE_BAO_CHAY : ['chữa cháy', 'chua chay'],
	TYPE_TIM_DOI : ['mời đối', 'giao lưu', 'bắt đối', 'tìm đối', 'sân nhà'],
	TYPE_TUYEN_THANH_VIEN : ['tìm một đội', 'tìm đội'],
	
	SPECIAL_CHARACTER : '0123456789%@$.,=+-!;/()*"&^:#|\n\t\'',
	STOP_WORDS : ['bị',
					'bởi',
					'cả',
					'các',
					'cái',
					'cần',
					'càng',
					'chỉ',
					'chiếc',
					'cho',
					'chứ',
					'chưa',
					'chuyện',
					'có',
					'có_thể',
					'cứ',
					'của',
					'cùng',
					'cũng',
					'đã',
					'đang',
					'đây',
					'để',
					'đến_nỗi',
					'đều',
					'điều',
					'do',
					'đó',
					'được',
					'dưới',
					'gì',
					'khi',
					'không',
					'là',
					'lại',
					'lên',
					'lúc',
					'mà',
					'mỗi',
					'một_cách',
					'nên',
					'nếu',
					'ngay',
					'nhiều',
					'như',
					'nhưng',
					'những',
					'nơi',
					'nữa',
					'phải',
					'qua',
					'ra',
					'rằng',
					'rằng',
					'rất',
					'rất',
					'rồi',
					'sẽ',
					'so',
					'sự',
					'tại',
					'theo',
					'thì',
					'trên',
					'trước',
					'từ',
					'từng',
					'và',
					'vẫn',
					'vào',
					'vậy',
					'vì',
					'việc',
					'với',
					'vừa']
};